# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestTable',
            new_name='AyouTable',
        ),
    ]
